server:
  port: 8601
spring:
  application:
    name: product_service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false&serverTimezone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true		